# Generated by Django 2.2.2 on 2019-06-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_cropper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecroppermodel',
            name='edited_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
